version: '3.8'

services:
  saint-streamer:
    image: saint-streamer
    container_name: saint-streamer
    hostname: saint-streamer
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8321:80
    environment:
      - APPLICATION_PORT=${APPLICATION_PORT}
      - KAFKA_SERVER_URI=${KAFKA_SERVER_URI}
      - KAFKA_SERVER_PORT=${KAFKA_SERVER_PORT}
      - KAFKA_CREATION_TOPIC_NAME=${KAFKA_CREATION_TOPIC_NAME}
      - KAFKA_UPDATE_TOPIC_NAME=${KAFKA_UPDATE_TOPIC_NAME}
      - KAFKA_DELETION_TOPIC_NAME=${KAFKA_DELETION_TOPIC_NAME}
      - MONGO_URI=${MONGO_URI}
      - DB_NAME=${DB_NAME}
      - COLLECTION_NAME=${COLLECTION_NAME}
    restart: always

networks:
  default:
    external: true
    name: local-network