apiVersion: apps/v1
kind: Deployment
metadata:
  name: saint-streamer
spec:
  selector:
    matchLabels:
      run: saint-streamer
  replicas: 2
  template:
    metadata:
      labels:
        run: saint-streamer
    spec:
      containers:
      - name: saint-streamer
        image: saint-streamer
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 100m
            memory: 200Mi